site_name: Spanish Marketing Guide
site_description: A comprehensive guide to marketing for Spanish-speaking audiences
# Replace with your actual GitHub Pages URL
site_url:  https://chrischasm.github.io/Marketing-Strategy/
# Replace with your actual GitHub repository URL
repo_url: https://github.com/ChrisChasm/Marketing-Strategy/
repo_name: <USERNAME>/<REPO_NAME> # Optional: displays the repo name

theme:
  name: material
  # Optional features
  logo: assets/logo.png # You'll need to create an assets/logo.png file
  favicon: assets/favicon.png # You'll need to create an assets/favicon.png file
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

# Navigation menu
nav:
  - Home: index.md
  - About: about.md
  - 1. Audience Insights:
      - 1.1 Personas: 1-audience-insights/1.1-personas.md
      - 1.2 Spiritual Openness: 1-audience-insights/1.2-spiritual-openness.md
      - 1.3 Digital Behavior: 1-audience-insights/1.3-digital-behavior.md
      - 1.4 Barriers & Motivators: 1-audience-insights/1.4-barriers-motivators.md
  - 2. Core Messaging:
      - 2.1 Key Themes: 2-core-messaging/2.1-key-themes.md
      - 2.2 Storytelling Framework: 2-core-messaging/2.2-storytelling-framework.md
      - 2.3 Value Propositions & CTA: 2-core-messaging/2.3-value-propositions-cta.md
      - 2.4 Language & Tone: 2-core-messaging/2.4-language-tone.md
  - 3. Channel Strategy:
      - 3.1 Organic Social: 3-channel-strategy/3.1-organic-social.md
      - 3.2 Paid Media: 3-channel-strategy/3.2-paid-media.md
      - 3.3 WhatsApp & Messenger: 3-channel-strategy/3.3-whatsapp-messenger.md
      - 3.4 Email & SMS: 3-channel-strategy/3.4-email-sms.md
      - 3.5 Influencer Collaboration: 3-channel-strategy/3.5-influencer-collaboration.md
      - 3.6 Events & Webinars: 3-channel-strategy/3.6-events-webinars.md
  - 4. Marketing Funnel:
      - 4.1 Funnel Stages: 4-marketing-funnel/4.1-funnel-stages.md
      - 4.2 Entry Points & Lead Magnets: 4-marketing-funnel/4.2-entry-points-lead-magnets.md
      - 4.3 Content Strategy: 4-marketing-funnel/4.3-content-strategy.md
      - 4.4 Retargeting & Nurturing: 4-marketing-funnel/4.4-retargeting-nurturing.md
  - 5. Landing Page:
      - 5.1 Conversion Goals: 5-landing-page/5.1-conversion-goals.md
      - 5.2 Page Architecture: 5-landing-page/5.2-page-architecture.md
      - 5.3 A/B Testing: 5-landing-page/5.3-ab-testing.md
      - 5.4 Tracking Conversions: 5-landing-page/5.4-tracking-conversions.md
      - 5.5 Integrations: 5-landing-page/5.5-integrations.md
  - 6. Creative Assets:
      - 6.1 Ad Examples: 6-creative-assets/6.1-ad-examples.md
      - 6.2 Social Templates: 6-creative-assets/6.2-social-templates.md
      - 6.3 Email Copy: 6-creative-assets/6.3-email-copy.md
      - 6.4 Landing Page Blocks: 6-creative-assets/6.4-landing-page-blocks.md
      - 6.5 Swipe File Index: 6-creative-assets/6.5-swipe-file-index.md
  - 7. Measurement & Optimization:
      - 7.1 KPIs: 7-measurement-optimization/7.1-kpis.md
      - 7.2 Dashboard Setup: 7-measurement-optimization/7.2-dashboard-setup.md
      - 7.3 Iteration Loop: 7-measurement-optimization/7.3-iteration-loop.md

# Plugins
plugins:
  - search # Required for search functionality

# Optional: Add custom CSS or JavaScript
# extra_css:
#   - stylesheets/extra.css
# extra_javascript:
#   - javascripts/extra.js

# Markdown extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 